### PR TITLE
Add segid()

### PR DESCRIPTION
**Pull request by koheiw**
Add `segid()` to discourage users to access directly to the system docvars (#2199)

### CODE REVIEW

**Comment by koheiw** [comment]
@kbenoit I am not sure what is happening in Github actions, but this PR should pass all the checks.

**Comment by kbenoit** [comment]
> @kbenoit I am not sure what is happening in Github actions, but this PR should pass all the checks.

Not sure either, but the reason I disabled that test on Linux was because in late November, our build started failing on the linux dev branches due to ongoing changes in the **Matrix** package (which caused us issues since late summer) and due to some R changes. I could not figure out the nuances from the tests, which had to do with Matrix object class coercions and how dimension names were preserved (or not), so I simply disabled the test on the failing platforms since I was getting dire warnings in early December from CRAN about the package being removed. I agree it's time to sort this out now. Sometimes things start breaking but later seem to be fixed again for the dev builds.

**Comment by kbenoit** [comment]
> @kbenoit I am not sure what is happening in Github actions, but this PR should pass all the checks.

Looks like codecov is failing and the ubuntu tests are not running as a result?
https://app.codecov.io/gh/quanteda/quanteda/pull/2201

**Comment by koheiw** [comment]
Matrix should be fine on Linux, at least on my machens. I will keep eyes on it.

Codecov of the project is irrelevant because the patch is 100%. Why don't we only use the patch coverage?

**Comment by kbenoit** [comment]
I'm happy with turning off the project codecov!

**Comment by koheiw** [comment]
The PR was not passing the tests because tests were not running. I fixed the Github action file and remove codecov/project from required list (although its is showing +0.02% increase this time).

**Review by kbenoit — APPROVED** [review]

**Pull request merged**
