### PR TITLE
Dev simil

### PR DESCRIPTION
**Pull request by koheiw**
Development of the core code for #1210 has been completed. Last thing is we should do is packaging.

### CODE REVIEW

**Comment by koheiw** [comment]
I agree that this is the way, but we will make a full transition to the sparse matrix eventually. So we need warn users that the `dist`(or `simil`) is deprecated, and will be removed in near future.

**Comment by koheiw** [comment]
It looks like this now
https://github.com/quanteda/quanteda/blob/6a02027c632e851fe64234e94a951b7abf651c6c/R/textstat_simil.R#L78-L93
I named the argument to switch the resulting object type `output`, because it is not the value that are affected. `textstat_simil()` sets a special class `simil`. I don't think there is no method for that, but kept only for backward compatibility.

**Comment by koheiw** [comment]
I believe the new similarity/distance functions are ready to ship. Use of `dist` object for similarity is totally inappropriate (it does not record diagonals), so we have to urge users to switch to `sparse` quickly.

**Comment by koheiw** [comment]
Thanks for reviewing @kbenoit. The C++ code always return `dgTMatrix` but we can use `dgCMatrix`. I didn't use the latter because compression takes sometime (only a few seconds, however). I can use `dsCMatrix` or `dgCMatrix`.

I will check revdev, leaving argument naming and documentation with you.

**Comment by koheiw** [comment]
If we want to tell the users about important changes, we can print message as news when package is loaded.

**Comment by kbenoit** [comment]
OK with `NULL` then, and let's restore the full set of dist attributes to the return value (which means only adding `method` I think).

**Comment by kbenoit** [comment]
Also @koheiw can you pls check the `skip()`ed last test in the `test-textstat_proxy.R` since I was not clear under which conditions the sparse triangular versus symmetric matrix is returned. It might depend on conditions which is ol, but then I’d need to generalise the documentation which right now states dtCmatrix only.

**Comment by koheiw** [comment]
If `dist` is an object class, `sparseMatrix` is more appropriate than `sparsematrix`. I think we have quite a few camel-cased argument values.

**Comment by kbenoit** [comment]
I agree about `sparseMatrix`!  but I thought you would hate the camelCase. 😄

**Comment by koheiw** [comment]
I hate mixing camels and snakes, but I tolerate camels as far as they are argument values, not names.

**Comment by kbenoit** [comment]
OK all looking good now, except two more things. 

### 1. `diag = FALSE` when `value = `sparseMatrix`

For consistency, we should remove the diagonals in the second of these. Making it 0 sets it to `.` however and that's not really what we want, since this means zero in dist (correctly) but would mean 0 in simil (incorrectly). Better to make the diagonal NA if `diag = FALSE, value = "sparseMatrix")`.

```r
textstat_simil(test_mt, upper = TRUE, diag = FALSE, value = "dist")
#            2005-Bush 2009-Obama 2013-Obama 2017-Trump
# 2005-Bush             0.9142772  0.9366455  0.9432850
# 2009-Obama 0.9142772             0.9583689  0.9433585
# 2013-Obama 0.9366455  0.9583689             0.9431704
# 2017-Trump 0.9432850  0.9433585  0.9431704           

textstat_simil(test_mt, upper = TRUE, diag = FALSE, value = "sparse")
# 4 x 4 sparse Matrix of class "dsCMatrix"
#            2005-Bush 2009-Obama 2013-Obama 2017-Trump
# 2005-Bush  1.0000000  0.9142772  0.9366455  0.9432850
# 2009-Obama 0.9142772  1.0000000  0.9583689  0.9433585
# 2013-Obama 0.9366455  0.9583689  1.0000000  0.9431704
# 2017-Trump 0.9432850  0.9433585  0.9431704  1.0000000

(d <- textstat_dist(test_mt, upper = TRUE, diag = FALSE, value = "sparse"))
4 x 4 sparse Matrix of class "dsCMatrix"
           2005-Bush 2009-Obama 2013-Obama 2017-Trump
2005-Bush    .         73.55270   56.44466   56.75385
2009-Obama  73.55270    .         64.07808   73.23251
2013-Obama  56.44466   64.07808    .         46.87217
2017-Trump  56.75385   73.23251   46.87217    .      

diag(d) <- NA
d
# 4 x 4 sparse Matrix of class "dsCMatrix"
#            2005-Bush 2009-Obama 2013-Obama 2017-Trump
# 2005-Bush         NA   73.55270   56.44466   56.75385
# 2009-Obama  73.55270         NA   64.07808   73.23251
# 2013-Obama  56.44466   64.07808         NA   46.87217
# 2017-Trump  56.75385   73.23251   46.87217         NA
```

**Comment by koheiw** [comment]
We definitely need `rank` because we not always have prior knowledge of the distribution of similarity, and optimal thresholds differ document to document. If we don't have `rank`, we need to rerun the function with different `min_smil` many times, taking several hours in each run.

People should explore sparse distance matrices by https://github.com/quanteda/quanteda/issues/1210#issuecomment-425683076, but not by coercing to `dist`. I though users can easily write functions to create a list from a matrix, but we can add `as.list()` if it is not the case.  `as.list.dgCMatrix` works not only with a distance matrix but also a dfm (good or bad).

**Comment by kbenoit** [comment]
What if we integrate all the changes _except_ the `rank` for now, and discuss how to integrate it separately? We can leave underlying code in place to be reactivated. We should think more systematically about departing from a symmetric distance matrix since the possible return objects are too broad if we have a third now (or fourth). We can fix this later.

**Comment by koheiw** [comment]
Hide `rank` from the users, but make it available via `...`?

**Comment by kbenoit** [comment]
A solution to my objections would be to make it a global rank from the pairwise set, so that it could remain symmetric. If users want the top set within a document, they can use min or max with a threshold and then coerce to a list using the n. Would that work?

**Comment by koheiw** [comment]
No. Global ranking is not only useless but also requires saving all the values. We should give up symmetry as there are asymmetric measures like Kulback. This is the main reason why we should abandon `dist` object as soon as possible, and the **proxy** package does not return that object type. `dist` is too constrained.

**Comment by kbenoit** [comment]
That's what I thought (and can see from the C++ code).  We still have problems 2 and 3 above.

**proxy** does return a dist, with one more tag to indicate it's the identically formatted simil class.
```r
> proxy::dist(as.matrix(test_mt)) %>% class()
[1] "dist"
> proxy::simil(as.matrix(test_mt)) %>% class()
[1] "simil" "dist" 
> philentropy::distance(as.matrix(test_mt))
Metric: 'euclidean' using unit: 'log'.
         v1       v2       v3       v4
v1  0.00000 73.55270 56.44466 56.75385
v2 73.55270  0.00000 64.07808 73.23251
v3 56.44466 64.07808  0.00000 46.87217
v4 56.75385 73.23251 46.87217  0.00000
```
The last package has a ton of distance metrics BTW, and returns a symmetric (regular) matrix (which is easily coerced into a dist). dist remains a useful format because of the existing functions that use it (nearly all clustering methods) and the coercion methods to and from that exist. Its only disadvantage is that it cannot handle sparsity. For non-sparse distance measures, it's already efficient.

Coercion to dist from the dsCMatrix is also a bit problematic since it currently treats the blank cells as zero. And zeros mean very different things depending on the metric. I was thinking how to fix the sparse non-symmetric matrix returned with the current rank and realized that the problems run deeper. 

**HOWEVER** I realized my concerns are a bit overstated since we already return one non-symmetric object, the `dist_selection` we created for this. 
```r
> textstat_simil(test_mt, selection = c("2009-Obama", "2013-Obama"))
           2009-Obama 2013-Obama
2005-Bush   0.9142772  0.9366455
2009-Obama  1.0000000  0.9583689
2013-Obama  0.9583689  1.0000000
2017-Trump  0.9433585  0.9431704
> textstat_simil(test_mt, selection = c("2009-Obama", "2013-Obama")) %>% str()
 'dist_selection' num [1:4, 1:2] 0.914 1 0.958 0.943 0.937 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:4] "2005-Bush" "2009-Obama" "2013-Obama" "2017-Trump"
  ..$ : chr [1:2] "2009-Obama" "2013-Obama"
 - attr(*, "Labels")= chr [1:2] "2009-Obama" "2013-Obama"
 - attr(*, "Size")= int 2
 - attr(*, "method")= chr "correlation"
 - attr(*, "call")= language textstat_simil.dfm(x = test_mt, selection = c("2009-Obama", "2013-Obama"))
> textstat_simil(test_mt, selection = c("2009-Obama", "2013-Obama"), rank = 3)
4 x 2 sparse Matrix of class "dgCMatrix"
           2009-Obama 2013-Obama
2005-Bush   .          .        
2009-Obama  1.0000000  0.9583689
2013-Obama  0.9583689  1.0000000
2017-Trump  0.9433585  0.9431704
> textstat_simil(test_mt, selection = c("2009-Obama", "2013-Obama"), rank = 3) %>% as.list()
[[1]]
[1] 0

[[2]]
[1] 1
...
```
So to make the rank function work, we would want to class it as `distsparse_selection` and make an `as.list()` method that excluded the blanks. We should also class the `dsCMatrix` version and make a special `as.list()` method for it as well. 

And think about what values the missing cells should take. We should make a list of the outstanding issues and split them up.

**Comment by koheiw** [comment]
Making a new class `dist_sparse` is an option (we don't need `_selection` because `ncol(x) != nrow(x)` tells us about it) with `as.dist.dist_sparse()` and `as.list.dist_sparse()`.

**Comment by koheiw** [comment]
If we don't find a good way to integrate the new function, I will make a separate package called **sparseproxy** or something and upload to CRAN. Only advanced users will use `textstat_proxy()` anyway. **quanteda** will call it internally.

**Comment by koheiw** [comment]
Updated as per #1455 discussion.

**Comment by kbenoit** [comment]
I'm seeing compiler warnings:
```
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DARMA_DONT_PRINT_OPENMP_WARNING  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppParallel/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include" -I/usr/local/include  -DARMA_64BIT_WORD=1 -fPIC  -Wall -g -O2 -c simil_mt.cpp -o simil_mt.o
simil_mt.cpp:105:11: warning: unused variable 'nrow' [-Wunused-variable]
    uword nrow = mt1.n_rows;
          ^
simil_mt.cpp:310:11: warning: unused variable 'nrow' [-Wunused-variable]
    uword nrow = mt.n_rows;
          ^
2 warnings generated.
```

**Comment by kbenoit** [comment]
@koheiw This PR is ready to merge, but check that you are okay with 0e33de0 where I commented out the declarations for the unused `nrow` variables. (This could generate compiler warnings.)

:+1:

**Pull request merged**
