### PR TITLE
Issue 2432

### PR DESCRIPTION
**Pull request by koheiw**
For #2432

### CODE REVIEW

**Comment by kbenoit** [comment]
I'm running a revdepcheck now to see if making this change breaks anything...

**Comment by kbenoit** [comment]
It breaks **seededlda**:

## Newly broken

*   checking tests ...
    ```
      Running ‘spelling.R’
      Running ‘testthat.R’
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      ══ Failed tests ════════════════════════════════════════════════════════════════
      ── Failure ('test-internal.R:110:5'): tfm works with ngrams ────────────────────
      rowSums(seededlda:::tfm(dfmt1, dict)) not equal to c(un = 2, icc = 2, other = 0).
      2/3 mismatches (average diff: 1)
      [1] 1 - 2 == -1
    ...
      [2] 1 - 2 == -1
      ── Failure ('test-internal.R:115:5'): tfm works with ngrams ────────────────────
      rowSums(seededlda:::tfm(dfmt2, dict)) not equal to c(un = 2, icc = 2, other = 0).
      2/3 mismatches (average diff: 1)
      [1] 1 - 2 == -1
      [2] 1 - 2 == -1
      
      [ FAIL 2 | WARN 0 | SKIP 8 | PASS 181 ]
      Error: Test failures
      Execution halted
    ```

**Comment by koheiw** [comment]
That is the easiest package to fix!

**Review by kbenoit — APPROVED** [review]
OK, but please increment the version and explain this change in `NEWS.md` before merging.

We could add this a global option...

**Pull request merged**
