### PR TITLE
Deprecate convenience arguments in dfm()

### PR DESCRIPTION
**Pull request by koheiw**
For #2058. I  support the idea of deprecating `dfm.corpus()`, but I did not because it brakes many bad examples in the quickstart guide.

### CODE REVIEW

**Comment by kbenoit** [comment]
I was thinking that the best way to really clean this up and discourage the shortcuts would be to remove the options from the function signature, but recognise them if called, by looking for these in `...`. If found, we keep them operational but issue the warning. (We did this when we changed the `tokens()` arguments for v2.)

The only tricky one is `tolower = TRUE`. The question is whether to keep this in the function signature and `TRUE`, or to go hard-core are remove it too. The problem is that if we remove it, then we will break existing behaviour since we probably don't want an argument not listed, but deprecated and operational, to be actively changing the input object.

This is a good case for the quanteda_option we discussed somewhere in all of this...

So I'm suggesting at least for now, we:
- remove all but `tolower = TRUE` from `dfm()`, and `verbose`. And consider making this operate via a quanteda_option, but that should be in a separate PR since it could involve other changes.
- make all other arguments functional via `...` but with warnings
- deprecate `dfm.character()` and `dfm.corpus()`

So `dfm()` would work just on tokens and look like
```r
dfm(x, tolower = TRUE, verbose = quanteda_options("verbose"), ...)
```

**Comment by koheiw** [comment]
It makes sense to hide deprecated arguments. 

I would keep `tolower` becasue DFM should discard information about positions of tokens (i.e. the first word in sentences), but capitalization is not always about positions (i.e. proper names). In many non-European languages, lowercasing does not change anything. I would also keep `remove` in `dfm()` or add `remove_padding = FALSE` to it to remove paddings. I think it is extremely rare that people want to keep paddings in DFM as a feature, but making it `TRUE` would upset users.

**Comment by kbenoit** [comment]
How about we keep `remove` but change its default to `remove = ""` which removes pads?

**Comment by koheiw** [comment]
This is exactly why I think we need `remove`.

**Comment by kbenoit** [comment]
I started working on this yesterday and even small changes caused so much to start breaking. We might need to keep `remove` as is, but include the `remove = ""` in the examples. I'm happy to work more on this one.

**Comment by kbenoit** [comment]
Current state of the PR:
- Implemented all previous `dfm()` argument functionality, but as non-documented, deprecated arguments. Only `valuetype` and `case_insensitive` are not working now.
- I kept the default for `remove` to `NULL`, rather than make the default value `""`. We could change that, but it breaks a lot of tests (and therefore, previous behaviour).
- Added a new Rd page called `quanteda-deprecations` where we can detail the breaking changes, as well as how to set the `strictness_warning` if we go with that (and I strongly think we should). This can also be a section of the pkgdown site.
- I also removed the previously deprecated ability to pass a dfm as a `pattern` input to `dfm_select()`.
 
Still needed:
- deprecate `kwic()` for character and corpus inputs
- add more detail to `quanteda-deprecations.Rd`
- add tests for deprecation warnings

**Comment by koheiw** [comment]
What it the advantage of giving an option to suppress deprecation warnings? If users do not want to see warnings, they should update the code. If they postpone changes, they will notice the change when the functions/arguments are removed (and unable to make sure that the results are unchanged). It is better to make the deprecation messages more informative (e.g. add a link to a web page on how to update the code) than hiding them.

**Comment by kbenoit** [comment]
Advantage is to ease the user pain. I don’t want to abruptly break colleagues’ teaching code, student code, researcher code, or other package author’s code, if we can avoid it as easily as adding an option to make the effect more mild, initially. With an option that has three levels of warning, we can tighten the strictness in minor releases - 3.1, 3.2, etc. Agree on the need to be informative, that’s why I created the `quanteda-depreciations.Rd`. And we can write a vignette article about the breaking changes and other improvements in v3. 

Just take a look at our vignette articles - they pretty much all need changing because of our depreciations. (I only did the main English quickStart.Rmd so far.) If it affects this way, imagine how widely it affect users.

**Comment by koheiw** [comment]
I haven't see option to suppress deprecation code anywhere else. Without surprising users with warning messages, they do not update their code (I also do not think deprecation messages break users code). If you want to let users to keep using their old code, better not changing any behavior and release **quanteda3**. I prefer this approach than a slow transition.

**Comment by kbenoit** [comment]
Let's merge this and see how bad it is with revdepcheck and with our own vignettes. I'll test this on some instructional materials too that we've developed.

The only open question is whether we want to go fully extreme and remove the `remove` option too. But I think we decided above that we both think it's better to keep for now.

**Comment by koheiw** [comment]
Please do merge. Let's keep `remove` in `dfm()` until we decide to add `remove_padding` or something.

**Pull request merged**
