### PR TITLE
C++ implementation of keyness functions #1635 

### PR DESCRIPTION
**Pull request by koheiw**
This branch not only improve the performance but also reduce dependency on data.table. 

There are two issues

- It fails test for chi2 when `correction = "williams"` but I don't know if the expected values is correct.
- The C++ does not support `measure = "exact"` but I think we should drop the measure as it is computationally too expensive.

I kept the old code accessible when `old = TRUE`.

### CODE REVIEW

**Comment by kbenoit** [comment]
Great stuff.

But I'm seeing `NaN` in the example code. Dividing by 0 somewhere?

```r
> period <- ifelse(docvars(data_corpus_inaugural, "Year") < 1945, "pre-war", "post-war")
> dfmat1 <- dfm(data_corpus_inaugural, groups = period)
> head(dfmat1) # make sure 'post-war' is in the first row
Document-feature matrix of: 2 documents, 9,360 features (34.9% sparse).
          features
docs       fellow-citizens   of  the senate  and house representatives   : among
  post-war               0 1437 1988      2 1456     3               0 105    22
  pre-war               39 5666 8094     13 3854     8              19  29    86
          features
docs       vicissitudes
  post-war            0
  pre-war             5
[ reached max_nfeat ... 9,350 more features ]
> head(tstat1 <- textstat_keyness(dfmat1), 10)
           feature chi2   p n_target n_reference
1  fellow-citizens  NaN NaN        0          39
2               of  NaN NaN     1437        5666
3              the  NaN NaN     1988        8094
4           senate  NaN NaN        2          13
5              and  NaN NaN     1456        3854
6            house  NaN NaN        3           8
7  representatives  NaN NaN        0          19
8                :  NaN NaN      105          29
9            among  NaN NaN       22          86
10    vicissitudes  NaN NaN        0           5
> 
> tail(tstat1, 10)
         feature chi2   p n_target n_reference
9351 complaining  NaN NaN        1           0
9352     arrives  NaN NaN        1           0
9353   mysteries  NaN NaN        1           0
9354       brown  NaN NaN        1           0
9355       bleed  NaN NaN        1           0
9356       urban  NaN NaN        1           0
9357      sprawl  NaN NaN        1           0
9358   windswept  NaN NaN        1           0
9359    nebraska  NaN NaN        1           0
9360     ignored  NaN NaN        1           0
```

**Comment by koheiw** [comment]
It is strange. It works fine on my Linux:

```r
> # compare pre- v. post-war terms using grouping
> period <- ifelse(docvars(data_corpus_inaugural, "Year") < 1945, "pre-war", "post-war")
> dfmat1 <- dfm(data_corpus_inaugural, groups = period)
> head(dfmat1) # make sure 'post-war' is in the first row
Document-feature matrix of: 2 documents, 9,360 features (34.9% sparse).
          features
docs       fellow-citizens   of  the senate  and house representatives   : among vicissitudes
  post-war               0 1437 1988      2 1456     3               0 105    22            0
  pre-war               39 5666 8094     13 3854     8              19  29    86            5
[ reached max_nfeat ... 9,350 more features ]
> head(tstat1 <- textstat_keyness(dfmat1), 10)
     feature     chi2 p n_target n_reference
1         we 707.2185 0      960         779
2          . 230.9059 0     1804        3141
3          - 226.2633 0      239         155
4        our 190.4594 0      874        1307
5         us 187.4062 0      262         216
6          : 178.9971 0      105          29
```
Is your local branch up to date?

**Comment by kbenoit** [comment]
I'm getting this with any call to `textstat_keyness()`. (And of course it's all current.)

``` r
library("quanteda")
## Package version: 2.1.9000
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
## 
## Attaching package: 'quanteda'
## The following object is masked from 'package:utils':
## 
##     View
dfmt <- dfm(c(
  d1 = "b b b b b b b a a a",
  d2 = "a a a a a a a b b"
))
textstat_keyness(dfmt)
##   feature chi2   p n_target n_reference
## 1       b  NaN NaN        7           2
## 2       a  NaN NaN        3           7
```

I think this is a good opportunity to move from Travis/Appveyor to GitHub Actions for CI. I did this on https://github.com/quanteda/quanteda.sentiment and https://github.com/quanteda/quanteda.tidy for instance and it checks Linux, Windows, and macOS. See `?usethis::use_github_action_check_full()`. Shall I set that up?

**Comment by koheiw** [comment]
I think I know what was happening: there was no serial for loop for machines with RcppParallel disabled. Your machine might be. How does the start up messages say? You can check manually by `quanteda:::qatd_cpp_tbb_enabled()` .

**Comment by koheiw** [comment]
I like Github Actions much better than Travis (it is not working anymore).

**Comment by kbenoit** [comment]
```r
> quanteda:::qatd_cpp_tbb_enabled()
[1] TRUE
> quanteda_options()$threads
[1] 2
```

I'll make a branch that switches to Actions.

**Comment by koheiw** [comment]
Do you still see only NaN?

**Comment by kbenoit** [comment]
Yes still NaN.

**Comment by koheiw** [comment]
I found out that TBB does not work with `std::function` (used for lambda functions) consistently across platforms. I rewrote the code in the classic (and reliable) way.  It passes the tests on Rhub Mac:

https://builder.r-hub.io/status/quanteda.core_2.1.1.tar.gz-b2df6d2f42304f869b9c3cbc9dadbd8e
https://builder.r-hub.io/status/quanteda.core_2.1.1.tar.gz-24e56ba7d24b449993fb0a978f82ded2

**Comment by kbenoit** [comment]
:+1: I can verify based on my local CMD check that it's working now on macOS. 

I'd suggest that we keep "exact" method for now but add a note to the Rd that it's very slow. Should I add a note?

**Comment by koheiw** [comment]
We still have the "exact" option, but it just calls the R function.

**Comment by kbenoit** [comment]
that's fine. I've added the note already.

**Review by kbenoit — APPROVED** [review]

**Pull request merged**
