### PR TITLE
Issue 2322

### PR DESCRIPTION
**Pull request by koheiw**
Add a new argument for #2322. It is tentatively named `condition` but could be `cond`, `run_if`, `iff`, `filter` etc. I had an ambition to enable NSE but it did not because it over-complicate the functions. I am planing to add the same argument to `tokens_compound()`.

``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 4.0.0
#> Unicode version: 15.1
#> ICU version: 74.1
#> Parallel computing: 16 of 16 threads used.
#> See https://quanteda.io for tutorials and examples.
dat <- data.frame(text = c("R and C are languages",
                           "Windows (R), Quanteda (C)",
                           "Sizes are X=10, Y=20, Z=30"),
                  topic = c("language", "software", "hardware"),
                  month = c(NA, 4, 12))
corp <- corpus(dat)
toks <- tokens(corp)

toks1 <- tokens_select(toks, min_nchar = 2, condition = toks$topic != "language")
toks1
#> Tokens consisting of 3 documents and 2 docvars.
#> text1 :
#> [1] "R"         "and"       "C"         "are"       "languages"
#> 
#> text2 :
#> [1] "Windows"  "Quanteda"
#> 
#> text3 :
#> [1] "Sizes" "are"   "10"    "20"    "30"

docname <- docnames(toks)
toks2 <- toks %>% 
    tokens_select(c("R", "C"), condition = docname == "text1") %>% 
    tokens_select(c("windows", "quanteda"), condition = docname == "text2") %>% 
    tokens_select("\\d", valuetype = "regex", condition = docname == "text3")
toks2
#> Tokens consisting of 3 documents and 2 docvars.
#> text1 :
#> [1] "R" "C"
#> 
#> text2 :
#> [1] "Windows"  "Quanteda"
#> 
#> text3 :
#> [1] "10" "20" "30"

toks3 <- toks |>
    tokens_keep(c("R", "C"), condition = toks$topic == "language") %>% 
    tokens_remove(min_nchar = 6, condition = toks$topic != "language")
toks3
#> Tokens consisting of 3 documents and 2 docvars.
#> text1 :
#> [1] "R" "C"
#> 
#> text2 :
#> [1] "Windows"  "Quanteda"
#> 
#> text3 :
#> character(0)

toks4 <- toks |>
    tokens_remove(min_nchar = 2, condition = toks$month) |>
    tokens_remove(stopwords())
toks4
#> Tokens consisting of 3 documents and 2 docvars.
#> text1 :
#> [1] "R"         "C"         "languages"
#> 
#> text2 :
#> [1] "Windows"  "Quanteda"
#> 
#> text3 :
#> [1] "Sizes" "10"    "20"    "30"
```

<sup>Created on 2023-12-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by koheiw** [comment]
I added the `condition` argument to `tokens_compound()` and tokens_replace()`.

**Review by kbenoit — COMMENTED** [review]
Looks good. A few comments. 

1. What if call this something more descriptive? For instance, `document_mapif` or `document_mask`? I'm fine with the latter if you want to avoid tidyverse language. `condition` seems too general.  
2. Let's put the documentation for this in its own function and then @inheritParams it, like valuetype etc.
3. I like how it's positioned last, just before `verbose`. But then I noticed that `tokens_compound()` and `tokens_split()` have no verbose option. Should they?
4. This is added to `tokens_compound()` -- should it not also be added to `tokens_split()`?

**Comment by koheiw** [comment]
`condition` is too general but `document_mapif` are `document_mask` too long. Since not many people would use this, this argument can be less visible. My favorite is `iff` or `run_if` for this reason. It is not really mapping. 

I think documents should be processed when `TRUE` to be consistent with `tokens_subset()`, but `mask` is not clear what happens when `TRUE` (mask or unmask?).  Other possible names are `include_doc` or `execute`.

I can add the new argument to `tokens_split()`. Generally, verbose messages needs to be improved package wide.

**Comment by kbenoit** [comment]
Fair point on the use of "mask", it's ambiguous. What if we call it `map_if`, which has a recognisable precedent in a widely used package? (just as we adopted some of the **stringi** argument names) 

`?purrr::map_if`:

`.p` ...Only those elements where `.p` evaluates to `TRUE` will be modified

**Comment by kbenoit** [comment]
Also I think this should work without `exclusive = FALSE`. Sometimes you just want the tokens looked up and their keys.

**Comment by kbenoit** [comment]
How about:
- [ ] I change the argument to `map_if` and document this as suggested above
- [ ] You add this to `tokens_split()`
- [ ] I'll raise the verbose review as a new issue

**Comment by koheiw** [comment]
Mapping seems to imply switching between documents to assign (or function to apply) depending on a given condition. In our case, it is always the same document.

I have only minimally inspired by tidyverse packages, but `modify_if` sounds fine:

> modify_if() only modifies the elements of x that satisfy a predicate and leaves the others unchanged.

**Review by kbenoit — APPROVED** [review]

**Pull request merged**
