### PR TITLE
Add textstat_sentiment() with unified valence approach

### PR DESCRIPTION
**Pull request by kbenoit**
OK Sensei, hozwabout this approach.

* Everything is valence. What I called "polarity" earlier is all treated as a special case of valence, where all dictionary values within a key have the same valence scores. To emulate the "polarity" approach, these need to be assigned -1 and 1 for negative and positive, which means that if we feed it smoothed, logged counts, we can get the equivalent of log(p/n) (which is as you know my favourite sentiment scale for polar categories).
* Computing sentiment uses your approach to "flipping" the valence scores and making them into a dictionary, and then computing the dfm where the "features" are the valence scores. Then we can use `%*%` for the combination to the document level.
* It's all part of meta$object$valence - so normal items are unaffected
* We do all of the robustness not through overloading indexing operators etc, but simply by naming each valence score element, and matching those. Any value not valenced will not be counted.

Let me know what you think, and I can start rewriting the tests and making this as robust as possible.

Note: Replaces #1948

### Demonstration

``` r
library("quanteda")
## Package version: 2.0.2

# simple example
txt <- c(
  d1 = "Great, I really like positive statements, not bad!",
  d2 = "This crap movie sucks bad, I'm not happy about it!"
)
toks <- tokens(txt)

dict <- dictionary(list(
  positive = c("great", "really like", "positive"),
  neg_positive = c("not happy"),
  negative = c("crap", "sucks", "bad"),
  neg_negative = c("not bad")
))

tokens_lookup(toks, dict, nomatch = "other") %>%
  dfm()
## Document-feature matrix of: 2 documents, 5 features (30.0% sparse).
##     features
## docs positive neg_positive negative neg_negative other
##   d1        3            0        1            1     5
##   d2        0            1        3            0     7

# METHOD 1
valence(dict) <- c(positive = 1, negative = -1)
# internally:
valence(dict)
## $positive
##       great really like    positive 
##           1           1           1 
## 
## $negative
##  crap sucks   bad 
##    -1    -1    -1

textstat_sentiment(toks, dict)
##   doc_id sentiment
## 1     d1       0.5
## 2     d2      -1.0
valence(dict) <- c(positive = 2, neg_negative = 1, negative = -2, neg_positive = -1)
textstat_sentiment(toks, dict)
##   doc_id sentiment
## 1     d1      1.00
## 2     d2     -1.75

# METHOD 2
valence(dict) <- list(positive = c(1, 2, 1.5), negative = c(-2, -2, 1))
textstat_sentiment(toks, dict)
##   doc_id sentiment
## 1     d1     1.375
## 2     d2    -1.000
# or with named elements
valence(dict) <- list(
  positive = c(great = 1, "really like" = 2, positive = 1.5),
  negative = c(-2, -2, 1)
)
textstat_sentiment(toks, dict)
##   doc_id sentiment
## 1     d1     1.375
## 2     d2    -1.000
# does not matter if named elements are rearranged
valence(dict) <- list(
  positive = c("really like" = 2, positive = 1.5, great = 1),
  negative = c(-2, -2, 1)
)
textstat_sentiment(toks, dict)
##   doc_id sentiment
## 1     d1     1.375
## 2     d2    -1.000
# unamed 1:1 corresponding elements are automatically named
valence(dict)
## $positive
## really like    positive       great 
##         2.0         1.5         1.0 
## 
## $negative
##  crap sucks   bad 
##    -2    -2     1

# DEMONSTRATION: AFINN
afinn <- tidytext::get_sentiments(lexicon = c("afinn"))
data_dictionary_afinn <- dictionary(list(afinn = afinn$word))
valence(data_dictionary_afinn) <- list(afinn = afinn$value)
textstat_sentiment(toks, dictionary = data_dictionary_afinn)
##   doc_id sentiment
## 1     d1       1.0
## 2     d2      -1.5

inaugtoks <- tokens(tail(data_corpus_inaugural))
textstat_sentiment(inaugtoks, dictionary = data_dictionary_afinn)
##         doc_id sentiment
## 1 1997-Clinton 0.8932584
## 2    2001-Bush 0.6578947
## 3    2005-Bush 0.7461140
## 4   2009-Obama 0.3586957
## 5   2013-Obama 0.5732484
## 6   2017-Trump 1.0341880

# DEMONSTRATION: ANEW (multiple valenced categories)
anew <- read.delim(url("https://bit.ly/2zZ44w0"))
anew <- anew[!duplicated(anew$Word), ] # because some words repeat
data_dictionary_anew <- dictionary(list(
  pleasure = anew$Word,
  arousal = anew$Word,
  dominance = anew$Word
))
valence(data_dictionary_anew) <- list(
  pleasure = anew$ValMn,
  arousal = anew$AroMn,
  dominance = anew$DomMn
)
textstat_sentiment(inaugtoks, data_dictionary_anew["pleasure"])
##         doc_id sentiment
## 1 1997-Clinton  5.942169
## 2    2001-Bush  6.091330
## 3    2005-Bush  6.308839
## 4   2009-Obama  5.841437
## 5   2013-Obama  6.045129
## 6   2017-Trump  6.223944
textstat_sentiment(inaugtoks, data_dictionary_anew["arousal"])
##         doc_id sentiment
## 1 1997-Clinton  5.208068
## 2    2001-Bush  5.252523
## 3    2005-Bush  5.315839
## 4   2009-Obama  5.207523
## 5   2013-Obama  5.342878
## 6   2017-Trump  5.334413
```

### CODE REVIEW

**Comment by kbenoit** [comment]
My To Do list before I forget:
- [ ] tests and checking robustness. 

- [ ] Need to make sure that anything can be an element name, including in R <= 4.0.
- [ ] investigate how we could implement alternative sentiment aggregation functions, especially for the special "polarity" cases (where all values within a key are considered equivalent in terms of valence). How can we implement (p-n)/N versus (p-n)/(p+n) versus log(p/n) for starters? This includes really testing and understanding exactly how are the non-matches used in the current code.
- [ ] Should we warn if we have multiple valenced keys? Above, the first case below makes sense, but the second does not since it's combining valences across multiple keys - so a form of averaging pleasure, arousal, and dominance. We should either warn against this, or compute each key separately.
```r
> textstat_sentiment(inaugtoks, data_dictionary_anew["arousal"])
        doc_id sentiment
1 1997-Clinton  5.208068
2    2001-Bush  5.252523
3    2005-Bush  5.315839
4   2009-Obama  5.207523
5   2013-Obama  5.342878
6   2017-Trump  5.334413
> textstat_sentiment(inaugtoks, data_dictionary_anew)
        doc_id sentiment
1 1997-Clinton  5.498039
2    2001-Bush  5.614141
3    2005-Bush  5.757551
4   2009-Obama  5.460327
5   2013-Obama  5.606507
6   2017-Trump  5.701053
```
- [ ] Write an article under `vignettes/pkgdown` that walks through how to use this approach.
- [ ] Consider how we might build on this (in the future!) to implement valence shifters as per [VADER](https://github.com/cjhutto/vaderSentiment). (R implementations in [**vader**](https://cran.r-project.org/web/packages/vader/) and [**sentimentr**](https://github.com/trinker/sentimentr).

**Comment by koheiw** [comment]
I enjoyed running the demo. This is something I had in my mind when we discussed too. I am not sure how far you are trying to go in this branch, but here are my comments.

## List of list of vector/list structure

In the Laver and Garry dictionary, for example, there is a category "CULTURE". It has own words (people, war_in_iraq, civil_war) along with 3 sub-categories. If the valence meta is a list of vector/list, there might be a problem (I like the simpler structure). One solution would be disallowing nesting in dictionary with valence.

``` r
require(quanteda)
dict <- dictionary(file = "~/repo/quanteda/tests/data/dictionaries/laver-garry.cat")
dict["CULTURE"]
#> Dictionary object with 1 primary key entry and 2 nested levels.
#> - [CULTURE]:
#>   - people, war_in_iraq, civil_war
#>   - [CULTURE-HIGH]:
#>     - art, artistic, dance, galler*, museum*, music*, opera*, theatre*
#>   - [CULTURE-POPULAR]:
#>     - media
#>   - [SPORT]:
#>     - angler*

is.list(dict["CULTURE"])
#> [1] TRUE
length(dict["CULTURE"])
#> [1] 1
```

## Subletting of dictionary

I wonder what should happen to the valence meta, when dictionary is subset. Currently, the valence meta does not change. I think it is fine, but good to think if we should subset them too.

## Storage of valence

I noticed that even with the uniform valence, the dictionary values are copied and valence scores are repeated. 

```r
valence(dict) <- c(positive = 2, neg_negative = 1, negative = -2, neg_positive = -1)
```

```
 .. .. ..$ valence  :List of 4
  .. .. .. ..$ positive    : Named num [1:3] 2 2 2
  .. .. .. .. ..- attr(*, "names")= chr [1:3] "great" "really like" "positive"
  .. .. .. ..$ neg_negative: Named num 1
  .. .. .. .. ..- attr(*, "names")= chr "not bad"
  .. .. .. ..$ negative    : Named num [1:3] -2 -2 -2
  .. .. .. .. ..- attr(*, "names")= chr [1:3] "crap" "sucks" "bad"
  .. .. .. ..$ neg_positive: Named num -1
  .. .. .. .. ..- attr(*, "names")= chr "not happy"
```
 
In my view, uniform valence should be stored as a list without such expansion; valence scores should not have names even if them are non-uniform.

```
 .. .. ..$ valence  :List of 4
  .. .. .. ..$ positive    : num 2
  .. .. .. ..$ neg_negative: num 1
  .. .. .. ..$ negative    : num -2
  .. .. .. ..$ neg_positive: num -1
```

## Printing the dictionary

We can see valence scores using `valence()` but it would be nicer to show the scores in `print.dictionary2()`. This is probably for the future, however.

```r
Dictionary object with 4 key entries.
- [positive (2)]:
  - great, really like, positive
- [neg_positive (-1)]:
  - not happy
- [negative (-2)]:
  - crap, sucks, bad
- [neg_negative (1)]:
  - not bad
```

**Comment by kbenoit** [comment]
Great, I agree with all of those comments. Some I will try to implement in the PR, others can be tweaked later. I'll work on these and the To Do list stuff over the weekend, including an Article for the pkgdown site that we can use for feedback to refine this a bit once we and users have had a chance to use it more.

**Comment by kbenoit** [comment]
Moved to https://github.com/quanteda/quanteda.sentiment.

**Pull request closed without merging**
