### PR TITLE
Remove repeated whitespaces keeping \n and \t when what = 'fasterword'

### PR DESCRIPTION
**Pull request by koheiw**
#1221

### CODE REVIEW

**Comment by koheiw** [comment]
I am addressing #1225 in this PR. It was caused by poor handling of empty tokens that are produced when `what = fasterword`. For some reason, `tokens` was not removing all the empty tokens, but it does now.

**Comment by kbenoit** [comment]
Should these behaviours be different? Or is this a limitation of the splitting on whitespace?

```r
txt <- "\n \t  word"
tokens(txt, what = "word", remove_separators = FALSE)
# tokens from 1 document.
# text1 :
# [1] "\n"   " "    "\t"   " "    " "    "word"

tokens(txt, what = "fasterword", remove_separators = FALSE)
# tokens from 1 document.
# text1 :
# [1] "\n"   "\t"   "word"

tokens(txt, what = "fastestword", remove_separators = FALSE)
# tokens from 1 document.
# text1 :
# [1] "\n"   "\t"   "word"
```

**Comment by koheiw** [comment]
`stri_split_regex()` and `stri_split_fixed()` removes separators, so it is a limitation. If users want separators, they just use `what = word`.

**Comment by kbenoit** [comment]
Ah right - it even says that in the documentation. RTFM to myself!

**Pull request merged**
