### PR TITLE
Improve stability of dfm_trim()

### PR DESCRIPTION
**Pull request by kbenoit**
- fixes docfreq() to work even for weighted dfm objects.
- adds warning for leaving min_count default at 1 when using fractional docfreq values
- improves stability.

Addresses #1237.

Still leaves some behaviours that may be unexpected by some users, when trimming a weighted dfm with fractional values, or supplying partially fractional values as arguments. Related to #1181.

### CODE REVIEW

**Comment by koheiw** [comment]
`dfm_trim()` can be useful for trimming a weighted DFM, but this use case brings us back to #1181. Since fractional `min_count` and `max_count` are interpreted as percentiles, there is not way to remove feature with TFIDF scores lower than 1.0. 

I also think that it is strange to take marginals (column sums) of TFIDF scores. For a TFIDF-weighted DFM, adding a `dfm_weight(limit = t)` which fills cell less than `t` with zero, and make eventually remove features (when columns are all zero).

**Comment by kbenoit** [comment]
What if we add an o `dfm_trim(x, min_count = .01, literal_count = TRUE)` which means use the literal comparison of the count value to the cells. (This does not apply to docfreq.)

Or, we could call it: `count_type = c("proportion", "actual")` and if the min/max_count` value were > 1.0, then we would issue a warning and default to "actual". This will not change the current behaviour but then prints a warning for every count minimum! If we default to "actual" then it changes the behaviour for fractional values.

Aren't legacy issues fun. Welcome to > v1.0.

**Comment by koheiw** [comment]
To make consistent with `valuetype`, how about `counttype`? We need `c('raw', 'proportion', 'percentile')` or, in short, `c('raw', 'prop', 'perc')`.

**Comment by kbenoit** [comment]
We could keep the existing behaviour, if when 
```r
dfm_trim(x, min_count = .05)  # e.g.
```
and
```r
counttype = "raw" && min_count < 1 && x@weightTf == "count" && x@weightTf == "unary"
```
then we print a warning and call the function again using 
```r
dfm_trim(x, min_count = .05, counttype = "proportion")
```

I don't think we should use percentile since that's only different from proportion by a constant.

**Comment by kbenoit** [comment]
I'm going to accept this since it improves the way `dfm_trim()` currently operates, without changing hte behaviour. In the meantime I will work on improving how `dfm_trim()` operates with the proportion v. count issue as we discussed recently (and will open an issue for this).

**Pull request merged**
