### PR TITLE
Issue 1765

### PR DESCRIPTION
**Pull request by koheiw**
patch for #1765

### CODE REVIEW

**Comment by kbenoit** [comment]
This raises an interesting question: Should `tokens_replace()` ever be capable of removing a token? I would lean toward saying no, since:
1.  We have a function for that, called `tokens_remove()`, and should limit removal behaviour to that function. Replacement should allow replacement with `""` but not removal entirely, since that's not a replacement.  
2. We require the pattern and replacement to have the same length, but `character(0)` has length 0, so this affects our checks. (Although I think it only works if you wrap the `character(0)` in a list.)

**Comment by koheiw** [comment]
How about replacing `c("a", "b", "c")` with `c("e", "f")`? Substitution by a shorter sequence needs to remove something.

**Comment by koheiw** [comment]
Also the `tokens_lookup()` does the same type of substitution: `c("United", "States")` to `"US"`.

**Comment by kbenoit** [comment]
Let's talk this one through briefly, since the instructions (and my interpretation) are that the replacements are 1:1. From the .Rd:

> Substitute token types based on vectorized one-to-one matching. 

So would replacing `c("a", "b", "c")` with `c("e", "f")` have to take place within a list? So that the 1:1 are list elements?

**Pull request merged**
