### PR TITLE
Add Unicode normalization

### PR DESCRIPTION
**Pull request by koheiw**
#1640

### CODE REVIEW

**Comment by kbenoit** [comment]
This looks fine but what if rather than hard-wiring this, we gave the user a bit more control by adding an option
```r
quanteda_options(unicode_normalization = "nfc")
```
where the legal values would be those implemented in **stringi**, namely nfc, nfd, nfkc, nfkc_casefold, and nfkd?

**Comment by koheiw** [comment]
All the method call `corpus.character()` including `tokens.character()`:
https://github.com/quanteda/quanteda/blob/b86b775ea2be4e93f56b6cb1d0865fbb0869c8f4/R/tokens.R#L185-L187

I do not really understand the difference between nfc, nfd, nfkc, nfkc_casefold but I think nfc does very little (make characters look the same actually the same in Unicode).

**Comment by kbenoit** [comment]
Quite right on the corpus call from tokens! I thought I saw an example where this was skipped. Maybe I should return my coffee to the vendor since I think they slipped me a decaf... 😕 

On the Unicode normalizations, I don't know much about the differences either, so we should probably educate ourselves more before hardwiring the choice of nfc. Or, we just ask @gagolews... 😃 

In https://github.com/quanteda/readtext/issues/146 however I found that nkfc solved a ligature problem but that nfc did not.

``` r
txt <- "substantial investments in human and ﬁnancial 
resources for the eﬀect of earlier diagnosis of waﬄes."

# ligatures not normalized
cat(stringi::stri_trans_nfc(txt))
## substantial investments in human and ﬁnancial 
## resources for the eﬀect of earlier diagnosis of waﬄes.

# ligatures normalized
cat(stringi::stri_trans_nfkc(txt))
## substantial investments in human and financial 
## resources for the effect of earlier diagnosis of waffles.
```

**Comment by koheiw** [comment]
There is no harm to add the option if there is a use-case, but characters for `pattern` are always normalized by `stri_trans_nfc()`, so we should use this in corpus too until we add the option.

**Comment by gagolews** [comment]
BTW, it's not uncommon to call a series of normalizations, e.g., `nfkc; nfc`

**Comment by gagolews** [comment]
you can do that with a single call to `stri_trans_general(str, "nfkc; nfc") `

**Pull request merged**
