### PR TITLE
Reset weighting scheme when grouped

### PR DESCRIPTION
**Pull request by koheiw**
#1545

### CODE REVIEW

**Comment by kbenoit** [comment]
I’m not sure this is really a good “feature”. For instance summing a tf-idf or document frequency weight as part of a `dfm_group()` operation has never been a good idea, but then resetting the flag that indicates where the values came from originally makes it worse.

Maybe we could list the weight types that we think are appropriate for summing in `dfm_group()`? But my basic advice would be: don’t group a weighted dfm. Group first, then weight.

**Comment by koheiw** [comment]
At least, Boolean should me allowed, because grouping of Boolean DFM is counting number of documents with certain features. This is very useful and I do similar operation very often to get daily or monthly counts.

**Comment by kbenoit** [comment]
OK, here is what we can safely aggregate:

- sum: count, prop. 
- Boolean (we would just re-run this through `dfm_weight(x, scheme = “boolean”)`)

However these are likely to cause problems if that is not what a user wanted. What if we just issue a warning for all but count and prop, and let the user do the re-weighting?

**Comment by kbenoit** [comment]
OK here is my proposal to close this out.

1.  We keep perform the grouping and summing as normal for count and prop weighted dfms. 
2. We perform the summing for all other weight types, but issue a warning that these weights are no longer correct.
    - this includes "boolean", so that a user could get sums on the original Boolean weights, but could also convert again to Boolean using a `dfm_weight(x, "boolean")` where `x` has been `dfm_group()`ed.
3. We record a grouping slot to show whether (and how?) the dfm has been grouped. Since @koheiw has been working on grouping schemes esp in branch `dev-corpus2`, I won't get more specific than this at this point, except to raise this possibility in general terms.
3.  We add a `force = FALSE` to `dfm_weight()`, where if it is `TRUE`, we would weight an already weighted dfm, and overwrite the existing weight slot setting.

**Comment by kbenoit** [comment]
OK I thought we should put this PR to bed, so I implemented the following changes to `dfm_weight()` and `dfm_group()`:

- `dfm_weight()` will not weight an already-weighted dfm unless `force = TRUE`
- `dfm_group()` will not group a dfm that has been weighted non-count or non-prop or document-weighted as non-unary, unless `force = TRUE`
- adds tests
- updates `NEWS.md` about these changes

**Comment by koheiw** [comment]
I am fine with ti. Generally speaking, `force` is a good way to leave difficult decisions with users while avoiding errors. `textmodel_*` has `force` too but they are more or less the same, I think.

**Pull request merged**
