### PR TITLE
Fix Solaris problems breaking CRAN for v2.1.0

### LINKED ISSUE #1983: v2.1.0 breaks Solaris
I got a warning email from BDR regarding these errors on Solaris:
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/quanteda-00check.html

Can this be fixed in #1980 ?

### PR DESCRIPTION
**Pull request by kbenoit**
- Don't cache textstat_summary() result on SunOS/Solaris
- skip textstat_summary() cache tests on solaris
- Fixes #1983

Passes r-hub solaris (Oracle Solaris 10, x86, 32 bit, R-release) although still has the 

Warning in deparse(e[[2L]]) :
  it is not known that wchar_t is Unicode on this platform

warnings that we cannot do anything about.

### CODE REVIEW

**Comment by koheiw** [comment]
https://github.com/quanteda/quanteda/blob/6c2cd698ce08a36d65bcfd62fbd819d995932c8c/R/utils.R#L380-L381

I suspect that digest function cannot serialize objects sometimes on Solaris, but there is nothing wrong with in our R code here, so skipping the test seems to be the solution.

**Comment by koheiw** [comment]
Shall we merge #1973 too?

**Comment by koheiw** [comment]
After seeing the error messages more carefully, I am skeptical if it is due to the cashing. 

The first four errors do not involve in caching.
```
     ── 1. Error: corpus_segment works with blank before tag (@test-corpus_segment.R#
     error in evaluating the argument 'x' in selecting a method for function 'as.list': error in evaluating the argument 'x' in selecting a method for function 'which': Start of codes indicating failure. (U_ILLEGAL_ARGUMENT_ERROR)
     Backtrace:
     1. base::summary(corp_seg)
     18. base::.handleSimpleError(...)
     19. base:::h(simpleError(msg, call))
    
     ── 2. Error: adding summary info works (@test-meta.R#126) ─────────────────────
     error in evaluating the argument 'x' in selecting a method for function 'as.list': error in evaluating the argument 'x' in selecting a method for function 'which': Start of codes indicating failure. (U_ILLEGAL_ARGUMENT_ERROR)
     Backtrace:
     1. quanteda:::add_summary_metadata(corp)
     19. base::.handleSimpleError(...)
     20. base:::h(simpleError(msg, call))
    
     ── 3. Error: adding extended summary information works (@test-meta.R#181) ─────
     error in evaluating the argument 'x' in selecting a method for function 'as.list': error in evaluating the argument 'x' in selecting a method for function 'which': Start of codes indicating failure. (U_ILLEGAL_ARGUMENT_ERROR)
     Backtrace:
     1. quanteda:::add_summary_metadata(corp, extended = TRUE)
     19. base::.handleSimpleError(...)
     20. base:::h(simpleError(msg, call))
```
Even when caching is turned off, it errors
```
     ── 5. Error: summary chache counts hashtag and emoji correctly (@test-textstat_s
     error in evaluating the argument 'x' in selecting a method for function 'as.list': error in evaluating the argument 'x' in selecting a method for function 'which': Start of codes indicating failure. (U_ILLEGAL_ARGUMENT_ERROR)
     Backtrace:
     1. quanteda::textstat_summary(toks, cache = FALSE)
     15. base::.handleSimpleError(...)
     16. base:::h(simpleError(msg, call))
```

**Comment by kbenoit** [comment]
I checked this on r-hub Solaris yesterday and with these changes, it passed - and it passes in this form where no test was removed outside of skipping them on Solaris. 

It works now on Solaris because of https://github.com/quanteda/quanteda/pull/1987/files#diff-e1f5f8bb1b65a19bc08162ca1d6f1040R60

**Comment by kbenoit** [comment]
Had to skip the tests for Solaris in `test-cache.R` to make this new approach work, but after testing on r-hub, it's all ok now.

**Pull request merged**
