### PR TITLE
Issue 1213

### PR DESCRIPTION
**Pull request by koheiw**
Rewriting `textplot_keyness()` to address #1233, #1211, #1213.

### CODE REVIEW

**Comment by kbenoit** [comment]
In the example for `textplot_keyness()`, the following fails:
```r
textplot_keyness(dem_key, show_reference = FALSE)
## Error: Aesthetics must be either length 1 or the same as the data (20): x, y, xend, yend, colour
```

**Comment by koheiw** [comment]
I created two color schemes for our package using **colorspace**. These are palced in `test/misc/color.R`. The first color should work with all the plot including `textplot_network` so I kept it similar to `skyblue`. 

`quanteda_palette()`:
palette

`quanteda_palette2()`:
palette2

**Comment by kbenoit** [comment]
I like the palette idea very much, let's absorb this PR and then work with the `colour.R` idea as a separate branch.  

I think it's going too far to make the defaults a "quanteda blue" scheme, since it's not contrasty enough for some plots. Keyness plots should have two colours closer to opposite ends of the rgb wheel, not from the same slice. I'd be fine with using ggplot defaults! 

The `color` arguments throughout should take the same values that are legal in **ggplot2**, which can include the integer colours. Ours does not work with integer colors. Can we change this?
```r
textplot_keyness(dem_key, color = 2:3)
## Error: Continuous value supplied to discrete scale
```

I changed it to allow a vector of colours length > 3, in case someone wants to use an RColorBrewer palette for instance.

**Comment by kbenoit** [comment]
Please:

- [ ] review the colour changes to see if you can live them, and I promise a "quanteda blue" palette!
- [ ] make sure that `color` takes all ggplot legal values including integers, then change the @param documentation for that parameter
- [ ] add tests for `check_font()` in `utils.R`
- [ ] add roxygen documentation for `check_font()` in `utils.R`

**Pull request merged**
