### PR TITLE
Issue 1007

### PR DESCRIPTION
**Pull request by kbenoit**
Redoes the `textmodel_*()` functions to make their object output and behaviour consistent with the `lm/glm` family of models, including in particular the `predict`, `summary`, `print`, and `coef` methods.

Still needs to be done for `textmodel_affinity()`.

Solves #1007.

### CODE REVIEW

**Comment by kbenoit** [comment]
Still need to:
- [ ] fix naming and transition to S3 for `textmodel_ca()`, redo the code in `textplot_scale1d()` for these changes
- [ ] fix naming and transition to S3 for `textmodel_lsa()`
- [ ] fix naming and transition to S3 for `textmodel_affinity()`, as well as additional methods

**Comment by koheiw** [comment]
The first two look strange to me. `predict(ws)` should return a vector of fitted values (without the `predict.textmodel_wordscores` class). It is not only to make it similar to `lm` but to allow users to skip calculation of se. People working on large dataset might want fitted values (I do usually).
```
> predict(ws)
             fit         lwr         upr
R1 -1.317931e+00 -1.33106234 -1.30480034
R2 -7.395598e-01 -0.76196925 -0.71715035
R3 -8.673617e-18 -0.02352986  0.02352986
R4  7.395598e-01  0.71715035  0.76196925
R5  1.317931e+00  1.30480034  1.33106234
V1 -4.480591e-01 -0.47137808 -0.42474008
attr(,"class")
[1] "predict.textmodel_wordscores" "matrix"                      

> predict(ws, se.fit = TRUE)
$fit
             fit         lwr         upr
R1 -1.317931e+00 -1.33106234 -1.30480034
R2 -7.395598e-01 -0.76196925 -0.71715035
R3 -8.673617e-18 -0.02352986  0.02352986
R4  7.395598e-01  0.71715035  0.76196925
R5  1.317931e+00  1.30480034  1.33106234
V1 -4.480591e-01 -0.47137808 -0.42474008

$se.fit
[1] 0.006699613 0.011433605 0.012005250 0.011433605 0.006699613 0.011897667

attr(,"class")
[1] "predict.textmodel_wordscores" "list"                        

> predict(ws, se.fit = TRUE, interval = "confidence")
$fit
             fit         lwr         upr
R1 -1.317931e+00 -1.33106234 -1.30480034
R2 -7.395598e-01 -0.76196925 -0.71715035
R3 -8.673617e-18 -0.02352986  0.02352986
R4  7.395598e-01  0.71715035  0.76196925
R5  1.317931e+00  1.30480034  1.33106234
V1 -4.480591e-01 -0.47137808 -0.42474008

$se.fit
[1] 0.006699613 0.011433605 0.012005250 0.011433605 0.006699613 0.011897667

attr(,"class")
[1] "predict.textmodel_wordscores" "list" 
```

**Comment by kbenoit** [comment]
The predict method does return just a named vector of fitted values, when `se.fit = FALSE, interval = "none"`. I changed the default for interval but we could easily put the default back to `"none"`, which is how `predict.lm()` works.

Add the attribute is the dumb S3 way to let other methods know that it's a predicted object. Mainly, we need this for `textplot_scale1d()`. Might be able to figure out another way to trigger that function in an easy to use way, or we could define a `print.predict.textmodel` method that removes the attribute so that the user is not exposed to that ugliness.

**Comment by kbenoit** [comment]
Here we have a classic legacy dilemma with the output of `predict()`: if we match the existing (e.g.) `predict.lm()` behaviour, then we have an indeterminate output object type (vector, list, matrix, etc). 

The only way to maintain consistency would be always to return a list, and always to have fit be a matrix, even if it had a single column, but then that does not provide the simple vector of predicted values that you said you (and many other users) prefer esp. for large datasets.

So my vote is to mimic the existing idiom.

**Comment by koheiw** [comment]
As long as we use generic methods like `predict`, we cannot keep shapes of output objects the same. I am pleased to know that we can still get a simple vector, but not sure if we should change the default value in the generic method.

**Comment by kbenoit** [comment]
Fine if you want to revert the parameter default to `interval = c("none", "confidence")` but you will need to fix what it breaks in the tests/examples then, incl for `textplot_scale1d()` (but this will be simple). Users who want SEs for that plot will need to set either `se.fit = TRUE` or `interval = "confidence"`.

**Comment by koheiw** [comment]
textmodel_wordscore

- [ ] `summary`
- [ ] `coef`
- [ ] `coefficients`
- [ ] `predict`
- [ ] `print.predict`

textmodel_wordfish

- [ ] `summary`
- [ ] `coef`
- [ ] `coefficients`
- [ ] `predict`
- [ ] `print.predict`

textmodel_nb

- [ ] `summary`
- [ ] `coef`
- [ ] `coefficients`
- [ ] `predict`
- [ ] `print.predict`

**Comment by koheiw** [comment]
All the textmodels are S3 with new class labels. `textmodel_affinity` is almost done, but there is no `summary.textmodel_affinity()`. `print.textmodel_affinity()` also needs extra info.

**Pull request merged**
