### PR TITLE
Dev compound

### PR DESCRIPTION
**Pull request by koheiw**
Add `window` to compound. See #1797.

### CODE REVIEW

**Comment by kbenoit** [comment]
See #1797. If we adopt this, I think we would need
- a more clear description of the `window` argument in the help
- an example showing a simple use case. Why would someone need or want this?

**Comment by koheiw** [comment]
This is a way to avoid patterns like `phrase("* * *")` which is near impossible because the exponential increase in number of fixed combinations. Main usage will be compounding hyphens `c("x", "-", "y")` without `*` and negations `c("not", "x")` or `c("not", "y")`. I don't think many people use this but does not harm anyone either.

**Comment by koheiw** [comment]
I have it smarter to avoid removing padding. The main purpose of this function is in https://github.com/quanteda/quanteda/blob/f2fa75354d3222ab1a8c10a01e0fa6ff667b8d68/R/tokens.R#L515-L516

**Comment by koheiw** [comment]
``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 1.9.9000
#> Parallel computing: 2 of 4 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View
quanteda_options(threads = 4)
toks <- tokens(data_corpus_inaugural)

identical(
  as.list(tokens_compound(toks, phrase("not *"))),
  as.list(tokens_compound(toks, "not", window = c(0, 1)))
)
#> [1] TRUE

microbenchmark::microbenchmark(
  tokens_compound(toks, phrase("not *")),
  tokens_compound(toks, "not", window = c(0, 1)),
  times = 10
)
#> Unit: milliseconds
#>                                            expr       min        lq      mean
#>          tokens_compound(toks, phrase("not *")) 305.83083 311.09162 346.93148
#>  tokens_compound(toks, "not", window = c(0, 1))  76.57474  78.73434  90.42414
#>     median      uq      max neval
#>  344.98429 365.615 425.5151    10
#>   90.04657 100.535 105.1423    10
```

<sup>Created on 2019-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Pull request merged**
