### PR TITLE
V2 operators

### LINKED ISSUE #1789: Implement v2 core document index operators
This involves completing the implementation of the v2 operators, as described in https://github.com/quanteda/quanteda/wiki/indexing_core_objects.

Checklist:
- [x] `$.corpus`
- [x] `$.tokens`
- [x] `$.dfm`
- [x] print friendlier error message for `[[.dfm`
- [x] print friendlier error message for `[[.fcm`
- [x] print friendlier error message for `$.fcm`

(Separately) we need to deal also with #1625 .

Example code:
``` r
library("quanteda")
## Package version: 1.9.9000

# corpus

data_corpus_inaugural["1793-Washington"]
## Corpus consisting of 1 document and 3 docvars.
# returns character vector of texts
data_corpus_inaugural[["1793-Washington"]]
## [1] "Fellow citizens, I am again called upon by the voice of my country to execute the functions of its Chief Magistrate. When the occasion proper for it shall arrive, I shall endeavor to express the high sense I entertain of this distinguished honor, and of the confidence which has been reposed in me by the people of united America.\n\nPrevious to the execution of any official act of the President the Constitution requires an oath of office. This oath I am now about to take, and in your presence: That if it shall be found during my administration of the Government I have in any instance violated willingly or knowingly the injunctions thereof, I may (besides incurring constitutional punishment) be subject to the upbraidings of all who are now witnesses of the present solemn ceremony.\n\n "
# not working yet
data_corpus_inaugural$Year
## Error in data_corpus_inaugural$Year: $ operator is invalid for atomic vectors
```

``` r

toks <- tokens(data_corpus_inaugural)
# returns tokens
toks["1793-Washington"]
## tokens from 1 document.
## 1793-Washington :
##   [1] "Fellow"         "citizens"       ","              "I"             
##   [5] "am"             "again"          "called"         "upon"          
##   [9] "by"             "the"            "voice"          "of"            
##  [13] "my"             "country"        "to"             "execute"       
##  [17] "the"            "functions"      "of"             "its"           
##  [21] "Chief"          "Magistrate"     "."              "When"          
##  [25] "the"            "occasion"       "proper"         "for"           
##  [29] "it"             "shall"          "arrive"         ","             
##  [33] "I"              "shall"          "endeavor"       "to"            
##  [37] "express"        "the"            "high"           "sense"         
##  [41] "I"              "entertain"      "of"             "this"          
##  [45] "distinguished"  "honor"          ","              "and"           
##  [49] "of"             "the"            "confidence"     "which"         
##  [53] "has"            "been"           "reposed"        "in"            
##  [57] "me"             "by"             "the"            "people"        
##  [61] "of"             "united"         "America"        "."             
##  [65] "Previous"       "to"             "the"            "execution"     
##  [69] "of"             "any"            "official"       "act"           
##  [73] "of"             "the"            "President"      "the"           
##  [77] "Constitution"   "requires"       "an"             "oath"          
##  [81] "of"             "office"         "."              "This"          
##  [85] "oath"           "I"              "am"             "now"           
##  [89] "about"          "to"             "take"           ","             
##  [93] "and"            "in"             "your"           "presence"      
##  [97] ":"              "That"           "if"             "it"            
## [101] "shall"          "be"             "found"          "during"        
## [105] "my"             "administration" "of"             "the"           
## [109] "Government"     "I"              "have"           "in"            
## [113] "any"            "instance"       "violated"       "willingly"     
## [117] "or"             "knowingly"      "the"            "injunctions"   
## [121] "thereof"        ","              "I"              "may"           
## [125] "("              "besides"        "incurring"      "constitutional"
## [129] "punishment"     ")"              "be"             "subject"       
## [133] "to"             "the"            "upbraidings"    "of"            
## [137] "all"            "who"            "are"            "now"           
## [141] "witnesses"      "of"             "the"            "present"       
## [145] "solemn"         "ceremony"       "."
# returns character vector of tokens
toks[["1793-Washington"]]
##   [1] "Fellow"         "citizens"       ","              "I"             
##   [5] "am"             "again"          "called"         "upon"          
##   [9] "by"             "the"            "voice"          "of"            
##  [13] "my"             "country"        "to"             "execute"       
##  [17] "the"            "functions"      "of"             "its"           
##  [21] "Chief"          "Magistrate"     "."              "When"          
##  [25] "the"            "occasion"       "proper"         "for"           
##  [29] "it"             "shall"          "arrive"         ","             
##  [33] "I"              "shall"          "endeavor"       "to"            
##  [37] "express"        "the"            "high"           "sense"         
##  [41] "I"              "entertain"      "of"             "this"          
##  [45] "distinguished"  "honor"          ","              "and"           
##  [49] "of"             "the"            "confidence"     "which"         
##  [53] "has"            "been"           "reposed"        "in"            
##  [57] "me"             "by"             "the"            "people"        
##  [61] "of"             "united"         "America"        "."             
##  [65] "Previous"       "to"             "the"            "execution"     
##  [69] "of"             "any"            "official"       "act"           
##  [73] "of"             "the"            "President"      "the"           
##  [77] "Constitution"   "requires"       "an"             "oath"          
##  [81] "of"             "office"         "."              "This"          
##  [85] "oath"           "I"              "am"             "now"           
##  [89] "about"          "to"             "take"           ","             
##  [93] "and"            "in"             "your"           "presence"      
##  [97] ":"              "That"           "if"             "it"            
## [101] "shall"          "be"             "found"          "during"        
## [105] "my"             "administration" "of"             "the"           
## [109] "Government"     "I"              "have"           "in"            
## [113] "any"            "instance"       "violated"       "willingly"     
## [117] "or"             "knowingly"      "the"            "injunctions"   
## [121] "thereof"        ","              "I"              "may"           
## [125] "("              "besides"        "incurring"      "constitutional"
## [129] "punishment"     ")"              "be"             "subject"       
## [133] "to"             "the"            "upbraidings"    "of"            
## [137] "all"            "who"            "are"            "now"           
## [141] "witnesses"      "of"             "the"            "present"       
## [145] "solemn"         "ceremony"       "."
# not working yet
toks$Year
## Warning: '$.tokens' is deprecated.
## Use '[].tokens' instead.
## See help("Deprecated")
## character(0)
```

``` r

# "["
dfmat <- dfm(toks)
# returns 1 x nfeat(dfmat) dfm
dfmat["1793-Washington"]
## Document-feature matrix of: 1 document, 9,357 features (99.0% sparse).
# but this suggests it should return NA
as.matrix(dfmat)["1793-Washington"]
## [1] NA
# this also errors
as(dfmat, "dgTMatrix")["1793-Washington"]
## Error in if (any(as.logical(i))) {: missing value where TRUE/FALSE needed

# "[["
# undefined - we should print a friendlier error message
dfmat[["1793-Washington"]]
## Error in dfmat[["1793-Washington"]]: this S4 class is not subsettable

# "$"
dfmat$Year
## Error in dfmat$Year: $ operator not defined for this S4 class
```

``` r

# "["
fcmat <- fcm(dfm_trim(dfmat, min_termfreq = 20))
# returns 2 x nfeat(fcmat) dfm
fcmat[c("the", "and")]
## Feature co-occurrence matrix of: 2 by 763 features.
# but this suggests it should return NA
as.matrix(fcmat)[c("the", "and")]
## [1] NA NA
# this also errors
as(fcmat, "dgTMatrix")[c("the", "and")]
## Error in if (any(as.logical(i))) {: missing value where TRUE/FALSE needed

# "[["
# undefined - we should print a friendlier error message
fcmat[[c("the", "and")]]
## Error in fcmat[[c("the", "and")]]: this S4 class is not subsettable

# "$"
# undefined - we should print a friendlier error message
fcmat$Year
## Error in fcmat$Year: $ operator not defined for this S4 class
```

``` r

dict <- dictionary(list(
  christmas = c("Christmas", "Santa", "holiday"),
  opposition = c("Opposition", "reject", "notincorpus")
))
# $ - returns contents of list element (correct)
dict$opposition
## [1] "opposition"  "reject"      "notincorpus"
# [ - returns dictionary subset (correct)
dict["opposition"]
## Dictionary object with 1 key entry.
## - [opposition]:
##   - opposition, reject, notincorpus
# [[ - returns contents of list element (correct)
dict[["opposition"]]
## [1] "opposition"  "reject"      "notincorpus"
```

### PR DESCRIPTION
**Pull request by kbenoit**
- Implements `$` for docvar access and assignment, adds tests
- Adds tests for all operators defined in https://github.com/quanteda/quanteda/wiki/indexing_core_objects
- Fixes #1789

### CODE REVIEW

**Comment by kbenoit** [comment]
@koheiw should the default behaviour for using `$` to address a non-existent docvar be to return a `NULL` (as with data.frame) or should it return an error, as with `docvars(x, name)`?

```r
> data_corpus_inaugural$nonexistent
NULL
> docvars(data_corpus_inaugural, "nonexistent")
 Error in select_docvars(attr(x, "docvars"), field, user = TRUE, system = FALSE,  : 
  field(s) nonexistent not found 
```

**Comment by kbenoit** [comment]
Good point on the non-existent documents and the indexing via [ and [[.

For the duplicated  docnames, this is a deeper issue that I think we should resolve separately as part of https://github.com/quanteda/quanteda/issues/1625. This will apply to corpus, tokens, and dfm objects.

**Comment by koheiw** [comment]
I think the behavior for non-existent docvars should be the same as `docvars(x, name)`. Then, users can notice there is something wrong in the upstream.

**Comment by kbenoit** [comment]
What if we make 

```r
> docvars(data_corpus_inaugural, "none")
NULL
```

**Comment by koheiw** [comment]
Then
```r
dat$x <- docvars(data_corpus_inaugural, "none") 
```
kills `x`. I am not sure if this is problematic or not.

**Comment by kbenoit** [comment]
Well, it's consistent with other uses of `$`, which is an argument for `NULL` being returned for a name not found.

```r
> data_corpus_inaugural$none
NULL
> iris$none
NULL
> data.table::data.table(iris)$none
NULL
> list(a = 1:3, b = 4:6)$none
NULL
```

Docvars can already be removed by replacing an existing docvar with `NULL`. And non-existent docvars can be created through assignment using `docvars(x, "newdocvar")<- ` or  `$<-`.

**Comment by koheiw** [comment]
I see. Then better to return `NULL`.

**Pull request merged**
