### PR TITLE
Print Unicode and ICU versions

### PR DESCRIPTION
**Pull request by koheiw**
to make trouble shooting easier and make users aware of the differences. It also helps to address https://github.com/quanteda/quanteda.textstats/issues/24.

### CODE REVIEW

**Review by kbenoit — APPROVED** [review]
Good change. I wonder if we should check a user preference that could turn on silent messages by default, if they wish.

**Comment by koheiw** [comment]
Generally speaking, we should stop using `cat()` for messaging, because `suppressMessages()` does not work.

```
> suppressMessages(cat("aaaa"))
aaaa
> suppressMessages(message("aaaa"))
> 
```

**Comment by kbenoit** [comment]
Totally right on `cat()` - that's why we wrote `catm()` which wraps `message()`. We should replace `cat()` with that if we have forgotten to use it anywhere.

**Comment by koheiw** [comment]
Create an issue #2020

**Pull request merged**
