### PR TITLE
Add ties.method to textstat_frequency()

### PR DESCRIPTION
**Pull request by kbenoit**
Passes this through to `data.table::frank()`, but uses the `"random"` method for backward compatibility (with how `textstat_frequency()` operated before. 

Open questions:
- Should the default be something else? `"dense"` makes a lot of sense.
- Should we follow existing practice in `base::rank()` and `data.table::frank()` and call this argument `ties.method` or should we follow our general practice of avoiding argument names containing ".", and call this `ties_method`?

Solves #1634.

### CODE REVIEW

**Comment by kbenoit** [comment]
@stefan-mueller comments welcome

**Comment by koheiw** [comment]
`min` sounds the best because it is consistent with `termfreq_type = "rank"` in `dfm_trim()`:

https://github.com/quanteda/quanteda/blob/b86b775ea2be4e93f56b6cb1d0865fbb0869c8f4/R/dfm_trim.R#L172

**Comment by kbenoit** [comment]
True, I'd forgotten about that. That makes sense in `dfm_trim()` though because we are using the rank as a cutoff. When the rank is returned as information, then "min" is definitely not my favourite.

**Comment by stefan-mueller** [comment]
Looks good! I also tested various **ggplot2** examples for all values for `ties.method` and the plotting works fine.

**Comment by koheiw** [comment]
I am fine to let users to choose the method to break ties, but are you sure that the name of the argument is `ties.method` instead of `ties_method`?

**Comment by kbenoit** [comment]
How about this then:
* call it `ties_method`
* which of these rankings makes more sense, for the vector [9, 9, 20]:
    - 1, 1, 3 ("min": ties ranked equivalently, but recording the next value as the actual ordinal place)
    - 1, 1, 2 ("dense": ties ranked equivalently, but recording the next value as the next ordinal place)
    - 2, 1, 3 ("random", as one of the two possible outcomes)
    - 1, 2, 3 ("first", using the arbitrary order in which it is sorted before ranking)

I don't think there is a strong case to be made for "average", "max", or "last" but of course the user could supply these.

**Comment by kbenoit** [comment]
OK, I changed the argument name to `ties_method` and made `"min"` the default. I think this makes most sense, and it's consistent now with `termfreq_type = "rank"` in `dfm_trim()`.

**Pull request merged**
