### PR TITLE
Add vignette that reproduces Chapter 5.1  "Quantitative Social Science"

### PR DESCRIPTION
**Pull request by stefan-mueller**
See #1183.

### CODE REVIEW

**Comment by kbenoit** [comment]
For the assignment of authors in the prediction example, it would nice to add in a docvar for the Author, and use that instead.

**Comment by stefan-mueller** [comment]
See my changes above. Is that what you preferred? Happy to make more adjustments if required.

**Comment by stefan-mueller** [comment]
Can we merge this pull request or are additional changes required, @kbenoit?

**Comment by kbenoit** [comment]
I finally remembered to bring home my copy of _QSS_ so now will able to compare the vignette with the book. Should be done soon. The question is whether to translate the literal **tm** code as in the book into **quanteda**, or also to improve the code a bit further. (Probably a mixture of the two.)

**Pull request merged**
