### PR TITLE
Issue 2078

### PR DESCRIPTION
**Pull request by koheiw**
Add `corpus_group()` and export `tokens_group()` for #2078.

### CODE REVIEW

**Comment by kbenoit** [comment]
This is good but some work was already done in #2081. The `tokens_group()` exporting and cleanup, including moving the `fill` argument Rd, was done in dfab982. Also here, `corpus_group()` uses the older quoted docvar names for `groups`, but I can change that to make it consistent with the `tokens_group()` and `corpus_group()` in #2081. I'll merge that #2081 now and then we can clean this PR up. 

Should we go ahead and deprecate `texts()` as well in this PR, since
- `texts(corp)` is now the same as `as.character(corp)`, but the "as" method seems more consistent with our usage throughout the rest of the package for coercing to base objects; and
- `texts(corp, groups = "something")` is now available through `as.character(corpus_group(corp, groups = "something"))`?

**Comment by koheiw** [comment]
I did not make changes for NSE deliberately in this PR.

**Comment by kbenoit** [comment]
OK but you agree that we should treat `groups` the same for `corpus_groups()` as for the other group fns?

**Comment by koheiw** [comment]
Yes, all the `*_group()` should work the same way (there are even tests for that).

**Review by kbenoit — APPROVED** [review]
I'm happy with this. I changed `corpus_group()` and the tests to make it consistent with the other group functions. I also consolidated the documentation a bit more and made it consistent across the functions. 

Merge if you are happy with it.

**Pull request merged**
