### PR TITLE
Change output of textstat_simil/dist to sparse Matrix format

### LINKED ISSUE #1210: Add min threshold to textstat_dist()?

### LINKED ISSUE #1469: Conversion to Matrix to dist is talking too much time
More than half of the execution time of `textstat_simil()` is coming from object conversion :unamused: 
```r
> quanteda_options(threads = 8)
> mt <- dfm(data_corpus_inaugural)
> microbenchmark::microbenchmark(
+   textstat_simil_old(mt, margin = "features"),  
+   #textstat_simil(mt, margin = "features"),
+   #textstat_simil(mt, margin = "features", min_simil = 0.9),
+   textstat_simil(mt, margin = "features"),
+   textstat_proxy(mt, margin = "features", rank = 3),
+   #qlcMatrix::cosSparse(mt),
+   times = 10
+ )
Unit: milliseconds
                                              expr        min         lq       mean     median         uq        max neval
       textstat_simil_old(mt, margin = "features")  7251.1911  7261.6533  7481.1757  7381.5864  7471.9465  8520.6013    10
           textstat_simil(mt, margin = "features") 11935.1468 12059.3998 12184.3832 12215.5913 12300.8472 12398.1135    10
 textstat_proxy(mt, margin = "features", rank = 3)   549.5476   557.0611   565.2102   561.9871   571.3744   585.1749    10
```
screenshot_20181025_123351

### LINKED ISSUE #1472: Call for feedback on textstat_proxy()
We added ` textstat_proxy()` function for computing document similarity with minimum threshold, but kept it experimental until we decide the format of the resulting objects. There are technological discussion #1455 #1469 on the issue, but we want to learn users perspective.

~~Since the function is experimental, you can only access it using `quanteda:::textstat_proxy()`.~~

### LINKED ISSUE #1675: textstat_simil(proxy, method = "faith") should return 1.0 for similarity of a document with itself
All other measures of similarity return 1.0 for the similarity of a vector with itself. Except "Faith", which appears to penalize similarity as identical vectors grow in length. I suspect this is an error in the formula, unless I have misunderstood [Faith, D. P. (1983). Asymmetric binary similarity measures. Oecologia, 57(3), 287-290.](https://link.springer.com/article/10.1007/BF00377169). 

In Faith (1983) it states that the formula is (a + d/2) / n, where a is (TRUE, TRUE) for a match and d is (FALSE, FALSE). For a vector with itself, a = n and d = 0, which should evaluate to 1.0. But this is not what happens.

``` r
library("quanteda")
## Package version: 1.4.4

set.seed(100)
x <- rpois(1000, lambda = 3)
dfmat <- as.dfm(matrix(c(x, x), nrow = 2, byrow = TRUE))
textstat_simil(dfmat, method = "faith")
##       x     y similarity
## 1 text2 text1      0.972
## 2 text1 text1      0.972
## 3 text1 text2      0.972
## 4 text2 text2      0.972

dfmat <- as.dfm(matrix(c(x[1:300], x[1:300]), nrow = 2, byrow = TRUE))
textstat_simil(dfmat, method = "faith")
##       x     y similarity
## 1 text2 text1      0.975
## 2 text1 text1      0.975
## 3 text1 text2      0.975
## 4 text2 text2      0.975
```

### LINKED ISSUE #1689: Unstable behaviour in textstat_simil()
In rare cases, that cannot be reproduced by setting the seed, but can be discovered by re-running the code below, some values are different.

``` r
library("quanteda")
# matrix for testing
mt <- dfm(corpus_subset(data_corpus_inaugural, Year > 1980))
mt <- dfm_trim(mt, min_termfreq = 10)
res <- textstat_simil(mt, c(2, 4), margin = "documents")

set.seed(10)
resv <- list()
for (i in 1:1000) {
  resv[[i]] <- textstat_simil(mt, c(2, 4), margin = "documents")$similarity
}
rescols <- do.call(cbind, resv)

plot(rescols[12, ], type = "b", ylim = c(.8, 1))
```

``` r
plot(rescols[1, ], type = "b", ylim = c(.8, 1))
```

### PR DESCRIPTION
**Pull request by kbenoit**
This PR:

* Changes the output format of `textstat_simil()` and `textstat_dist()` to a specially classed `textstat_simildist` S4 object that inherits from sparse **Matrix** classes. There are child classes of this depending on whether it is a simil or dist object, whether the y dimension has been selected, and whether `min_simil > 0`.

    Class structure:

| object                      | based on      | `selection` | `min_simil` |
|-----------------------------|---------------|:-----------:|:-----------:|
| `textstat_simildist`        | dsparseMatrix |      -      |      -      |
| `textstat_simil`            | dsTMatrix     |      𝗑      |      0      |
| `textstat_simil_sel`        | dgTMatrix     |      ✓      |      0      |
| `textstat_simil_sparse`     | dsCMatrix     |      𝗑      |     > 0     |
| `textstat_simil_sel_sparse` | dgCMatrix     |      ✓      |     > 0     |
| `textstat_dist`             | dsTMatrix     |      𝗑      |      -      |
| `textstat_dist_sel`         | dgTMatrix     |      ✓      |      -      |

* Verifies that `as.dist()` and `as.matrix()` work on all of these objects, the former from **base** and the latter from the **Matrix** package functions for the parent sparse Matrix classes.

* Removes the `diag` and `upper` arguments from the `textstat_simil/dist()` functions. (However: We should probably trap and deprecate these via `...`.)

* Implements `as.list(x, sorted = TRUE, n = NULL, diag = FALSE, ...)` for the output objects, where `diag = TRUE` means that same-pair values (which are always either 0.0 or 1.0) are included.

* Implements `as.data.frame(x, diag = FALSE, upper = FALSE)` to convert the output object to a pairwise list that is identical the object output class that we developed for #1664. Setting `upper = TRUE` means that both (A, B) and (B, A) pairs are included.

* Implements `min_simil` option for `textstat_simil()`.

* Removes some methods that produced irregular results (e.g. "faith" and "kullback").

Closes #1675 
Closes #1469
Closes #1472 
Closes #1210 
Closes #1689
Closes #1675 

Still need to check: #1540, #1541 

Need to solve separately, although no longer an issue for `textstat_simil`: #1693

### CODE REVIEW

**Comment by koheiw** [comment]
There are too many classes (reminds me of `dfmSparse` and `dfmDense`). If you wrap a Matrix by a list, you only need a single S3 class for a simil/dist object.

**Comment by kbenoit** [comment]
But then you would need to write methods for every matrix operation for that list wrapper class, instead of using the ones already common to Matrix classes. It looks complex but the user will never need this information. Classing it this way preserves the symmetry (saving half the space) from just making them all dgCMatrix. 

So: it’s as simple as a normal matrix for the user, but gives us the hidden control we need.

I like the validators and more robust slots from the S4 classes too.

**Comment by koheiw** [comment]
I thought you want to stop people from doing matrix operation (as in data.frame), although we can define `as.Matrix()` to make it possible.  I prefer Matrix objects without custom class labels.

**Comment by koheiw** [comment]
The best solution would be to ask a third-party package to do the conversation to data.frame. https://github.com/tidymodels/broom/issues/470

**Comment by koheiw** [comment]
I am note sure why `update-simil-Matrix` was merged. I did not mean to do this by #1699...

**Pull request merged**
