### PR TITLE
Fix 1607

### LINKED ISSUE #1607: update help on `tokens_compound`?
## Describe the bug

Help page for `tokens_compound` says `pattern` arg can be "a character vector, list of character vectors, dictionary, collocations, or dfm." but character vectors don't seem to work.

## Reproducible code

Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds`.
```r
tokens_compound(tokens("United States of America"), pattern = list(c("united", "states", "of", "america"))) # compounds
tokens_compound(tokens("United States of America"), pattern = c("united", "states", "of", "america")) # doesn't compound
```

## Expected behavior

Both cases compound to `"United_States_of_America"`

## System information

Please run `sessionInfo()` and paste the output.
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rvest_0.3.2    xml2_1.2.0     quanteda_1.3.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18       bindr_0.1.1        pillar_1.3.0       compiler_3.5.1    
 [5] plyr_1.8.4         stopwords_0.9.0    tools_3.5.1        digest_0.6.16     
 [9] lubridate_1.7.4    evaluate_0.11      tibble_1.4.2       gtable_0.2.0      
[13] lattice_0.20-35    pkgconfig_2.0.2    rlang_0.2.2.9000   fastmatch_1.1-0   
[17] Matrix_1.2-14      rstudioapi_0.7     curl_3.2           yaml_2.2.0        
[21] bindrcpp_0.2.2     httr_1.3.1         stringr_1.3.1      dplyr_0.7.6       
[25] knitr_1.20         hms_0.4.2          tidyselect_0.2.4   rprojroot_1.3-2   
[29] grid_3.5.1         glue_1.3.0         data.table_1.11.4  R6_2.2.2          
[33] rmarkdown_1.10     selectr_0.4-1      spacyr_0.9.91      purrr_0.2.5       
[37] readr_1.1.1        ggplot2_3.0.0      magrittr_1.5       backports_1.1.2   
[41] scales_1.0.0       htmltools_0.3.6    assertthat_0.2.0   colorspace_1.3-2  
[45] stringi_1.2.4      RcppParallel_4.4.1 lazyeval_0.2.1     munsell_0.5.0     
[49] crayon_1.3.4   
```

## Additional info

Probably just the help page needs adjusting. I don't think there's anything particularly wrong with not working with character vectors, but perhaps you intended it to.

### PR DESCRIPTION
**Pull request by kbenoit**
I updated the documentation to make it more straightforward, with examples for each pattern type. @conjugateprior does this clarify?

Fixes #1607.

(But I'd sill like to see #1608 solved!)

### CODE REVIEW

**Comment by kbenoit** [comment]
Feel free to add that explanation. The problem is that most of the time, we will want case-insensitive matches, since collocations are likely to be case insensitive.

Maybe a workaround internally would be to create 2^n case variants for fixed matching, where the variants are lower and upper case versions of the same words, and n is the collocation length?

**Comment by koheiw** [comment]
If collocations are discovered in a tokens object, and `tokens_compound()` is used to modify tokens, case-sensitive match is the best. If users do not know, `textstat_collocations()` will earn a reputation that it is impractically slow.

The real problem is that `textstat_collocations()` does lower-casing internally then cases of users' tokens object and the result from `textstat_collocations()` do not match. We should remove that argument and let users lowercase themselves by `tokens_tolower()`.

**Comment by kbenoit** [comment]
I just added a note about performance. Why is the performance hit for collocations specifically if we can easily convert to an equivalent list? If the performance hit is the same for all `pattern` types, then we should change the note to state that `case_insensitive = TRUE` is just inherently much slower.

``` r
library("quanteda", warn.conflicts = FALSE)
## Package version: 1.4.1
## Parallel computing: 2 of 12 threads used.
## See https://quanteda.io for tutorials and examples.
txt <- "The United Kingdom is leaving the European Union."
toks <- tokens(txt, remove_punct = TRUE)

tokens_compound(toks, phrase(c("United Kingdom", "European Union")),
  case_insensitive = TRUE
)
## tokens from 1 document.
## text1 :
## [1] "The"            "United_Kingdom" "is"             "leaving"       
## [5] "the"            "European_Union"

colls <- tokens("The new European Union is not the old European Union.") %>%
  textstat_collocations(size = 2, min_count = 1, tolower = FALSE)
tokens_compound(toks, phrase(colls$collocation),
  case_insensitive = TRUE
)
## tokens from 1 document.
## text1 :
## [1] "The"            "United"         "Kingdom"        "is"            
## [5] "leaving"        "the"            "European_Union"
```

**Comment by koheiw** [comment]
I took a proper benchmark:

```r
require(quanteda)
quanteda_options(threads = 8)

corp <- readRDS("/home/kohei/Documents/Brexit/Data/data_corpus_guardian_2016.RDS")
toks <- tokens(corp)
toks_lower <- tokens_tolower(toks)

coll <- toks_lower %>% 
        tokens_remove(stopwords(), padding = TRUE) %>% 
        tokens_select("^\\w+$", valuetype = "regex", padding = TRUE) %>% 
        textstat_collocations(min_count = 100, tolower = FALSE)


microbenchmark::microbenchmark(
    tokens_compound(toks, coll, case_insensitive = TRUE),
    tokens_compound(toks_lower, coll, case_insensitive = FALSE),
    times = 10
)
```
`patter2id()` is doing better job than I though, so we do not need to worry about it too much.
```
Unit: seconds
                                                        expr      min       lq     mean   median       uq      max neval
        tokens_compound(toks, coll, case_insensitive = TRUE) 5.975838 6.124869 6.256155 6.253196 6.301904 6.689778    10
 tokens_compound(toks_lower, coll, case_insensitive = FALSE) 3.899954 4.131187 4.383006 4.294767 4.800157 4.971474    10
> nrow(coll)
[1] 9818
> head(coll)
      collocation count count_nested length   lambda        z
1       last year 17838            0      2 6.071388 621.7806
2    donald trump 22377            0      2 7.843557 572.4416
3  prime minister 24054            0      2 9.689098 551.0187
4   david cameron  8944            0      2 8.019258 497.4722
5 hillary clinton 13457            0      2 8.500789 488.4760
6       last week 10042            0      2 6.076385 484.0451
> ndoc(corp)
[1] 60045
```
I will make a small change, however.

**Pull request merged**
