### PR TITLE
Fix test to make it independent of the order of x values

### PR DESCRIPTION
**Pull request by koheiw**
#1491 was puzzling because it does not happen on any of my Linux machines, but the answer was simple: TBB works a bit differently on the CRAN machine with Xeon CPU.

### CODE REVIEW

**Comment by koheiw** [comment]
I should have explain to you better, but this is what your stability test should look like. The problem was that the `x` values looks random, when you ignore `i` and `j` (they change correspondingly). However it is not, when it is converted to a dense matrix. 
```r
result <- data.frame()
colnames(result) <- paste0("v", 1:4)
for (i in seq_len(n)) {
    out <- quanteda:::qatd_cpp_similarity_linear(t(mt), 1, seq_len(ndoc(mt)), ndoc(mt), -1)
    result <- rbind(result, as.numeric(as.matrix(out)))
}
unique(result)
#   v1 v2 v3 v4
# 1  1  0  0  1
```

**Comment by kbenoit** [comment]
Ok... But we can fix that in the output. The i and j values always sorted in address order in a sparse T matrix, so we should so the same.

There is still the problem 1 above though.

**Comment by koheiw** [comment]
On problem 1, it is `dist` object's problem: do not record diagonals...
```r
toks <- tokens(c(doc1 = 'a b c', doc2 = 'd e f'))
mt <- dfm(toks)

textstat_simil(mt, method = "cosine") %>% as.matrix()
#      doc1 doc2
# doc1    0    0
# doc2    0    0
textstat_proxy(mt, method = "cosine") %>% as.matrix()
#      doc1 doc2
# doc1    1    0
# doc2    0    1
```
`dgTMatrix` is perfectly fine without sorting. I could sort but there might be performance penalty.

```r
> tri <- sparseMatrix(i = c(1,3:8), 
+                     j = c(9,2,6:10), 
+                     x = 7 * (1:7), giveCsparse = FALSE)
> 
> tri
8 x 10 sparse Matrix of class "dgTMatrix"
                              
[1,] .  . . . .  .  .  .  7  .
[2,] .  . . . .  .  .  .  .  .
[3,] . 14 . . .  .  .  .  .  .
[4,] .  . . . . 21  .  .  .  .
[5,] .  . . . .  . 28  .  .  .
[6,] .  . . . .  .  . 35  .  .
[7,] .  . . . .  .  .  . 42  .
[8,] .  . . . .  .  .  .  . 49
> tri@x
[1]  7 14 21 28 35 42 49
> 
> tri_rev <- sparseMatrix(i = rev(c(1,3:8)), 
+                         j = rev(c(9,2,6:10)), 
+                         x = rev(7 * (1:7)), giveCsparse = FALSE)
> 
> 
> tri_rev
8 x 10 sparse Matrix of class "dgTMatrix"
                              
[1,] .  . . . .  .  .  .  7  .
[2,] .  . . . .  .  .  .  .  .
[3,] . 14 . . .  .  .  .  .  .
[4,] .  . . . . 21  .  .  .  .
[5,] .  . . . .  . 28  .  .  .
[6,] .  . . . .  .  . 35  .  .
[7,] .  . . . .  .  .  . 42  .
[8,] .  . . . .  .  .  .  . 49
> tri_rev@x
[1] 49 42 35 28 21 14  7
> 
```

**Comment by kbenoit** [comment]
OK, I get it now, but will raise a separate issue about as.matrix.dist() and what we should return when `diag = TRUE`.

**Comment by koheiw** [comment]
the `as.matrix.dist()` issue would be difficult one :grimacing:

**Comment by kbenoit** [comment]
`as.matrix.dist()` is fine, it's the `as.matrix.simil()` that needed different handling.

`dsTMatrix` as a format is superior to `dist` and I agree we should make the switch, *but*:

1.  we need a way to handle the diagonal for the similarity types, same as #1494, since this is wrong:
```r
textstat_proxy(mt, method = "cosine") %>% as.dist(diag = TRUE)
#      doc1 doc2
# doc1    0     
# doc2    0    0
```

2. zeroes should be real zeros, not items we dropped because of thresholds. I still see no solution to #1455 using sparse matrix objects for this.

Anyway @koheiw please take a look at my fix and merge if you approve.

**Pull request merged**
