### PR TITLE
Issue 2399

### PR DESCRIPTION
**Pull request by koheiw**
Add `keep_unigrams` as discussed in #2399. Compared to other arguments of the function like `join` the name is rather long, so it could be just `keep`.

### CODE REVIEW

**Comment by koheiw** [comment]
```
> txt2 <- "we like high quality sound"
> toks2 <- tokens(txt2)
> seqs2 <- phrase(c("high quality", "quality sound"))
> 
> tokens_compound(toks2, seqs2, join = TRUE, keep_unigrams = TRUE)
Tokens consisting of 1 document.
text1 :
[1] "we"                 "like"               "high"               "quality"            "sound"             
[6] "high_quality_sound"

> tokens_compound(toks2, seqs2, join = FALSE, keep_unigrams = TRUE)
Tokens consisting of 1 document.
text1 :
[1] "we"            "like"          "high"          "high_quality"  "quality"       "quality_sound"
[7] "sound"        
```

**Review by kbenoit — APPROVED** [review]

**Comment by koheiw** [comment]
I wasn't entirely sure about the order of original and compounded tokens. Do you think it is OK as is?

**Comment by kbenoit** [comment]
I thought about that too... It doesn't matter a great deal, but it would probably make sense to insert the compounds only after the unigrams.

So above, the first example is fine, but the second example ought to be:

```r
> tokens_compound(toks2, seqs2, join = FALSE, keep_unigrams = TRUE)
Tokens consisting of 1 document.
text1 :
[1] "we"            "like"          "high"          "quality"       "sound"    "high_quality" 
[7] "quality_sound"
```

**Comment by koheiw** [comment]
I think I can change to this way. I will issue a separate PR.

**Comment by kbenoit** [comment]
Then this PR seems ready for merge. 🛫

**Pull request merged**
