### PR TITLE
Deprecate texts() and texts<-

### PR DESCRIPTION
**Pull request by kbenoit**
Deprecate `texts()` and `texts<-`. Also:
- moves these functions to texts.R, makes them internal only, and marks them as deprecated in the title
- reorganizes main object methods source files
- creates a more consistent man page for corpus coercion and checking methods (is.corpus, as.corpus)
- updates NEWS
- changes examples, tests, and internal code to use as.character.corpus() instead of texts()
- makes as.character.corpus() independent and texts() now calls as.character(), instead of the other way around as it was previously.

Solves #2076.

### CODE REVIEW

**Comment by koheiw** [comment]
It makes sense to use `as.character()` instead of `texts()`. How about defining `corpus<-`? Do you want to prevent users from changing texts in a corpus entirely?

**Comment by kbenoit** [comment]
Interestingly the "[.corpus" already works for texts replacement, without messing up metadata. But it has to be used, even if the index is empty.

``` r
library("quanteda")
## Package version: 2.9.9000
## Unicode version: 10.0
## ICU version: 61.1
## Parallel computing: 12 of 12 threads used.
## See https://quanteda.io for tutorials and examples.

corp <- corpus(letters[1:3], docvars = data.frame(dvar = 101:103))
corp
## Corpus consisting of 3 documents and 1 docvar.
## text1 :
## "a"
## 
## text2 :
## "b"
## 
## text3 :
## "c"

corp[] <- c("new1", "new2", "new3")
corp
## Corpus consisting of 3 documents and 1 docvar.
## text1 :
## "new1"
## 
## text2 :
## "new2"
## 
## text3 :
## "new3"
docvars(corp)
##   dvar
## 1  101
## 2  102
## 3  103

corp[2] <- "second text"
corp
## Corpus consisting of 3 documents and 1 docvar.
## text1 :
## "new1"
## 
## text2 :
## "second text"
## 
## text3 :
## "new3"
docvars(corp)
##   dvar
## 1  101
## 2  102
## 3  103

corp <- paste0("text", 1:3)
corp
## [1] "text1" "text2" "text3"
```

But without the `[` it simply replaces the entire object. It's logical but not obvious. Perhaps we should document this more.

It's also possible we could just hide `texts()` and `texts()<-` now but turn off the deprecation warnings. They seem to get used a lot in our examples and our own code.

<sup>Created on 2021-03-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by koheiw** [comment]
I came across a package that actively use empty `[]` long time ago (probably network analysis package). I kind of liked it but it is very new to many users. I think we should some how allow users to modify character strings in a corpus.

**Comment by kbenoit** [comment]
Agreed. But that functionality works fine now using `corp[] <-` with no or any valid indexes in the `[]`.

**Review by koheiw — APPROVED** [review]
OK, let's move on with `corp[]`. The manual page for `[` says:

> An empty index selects all values: this is most often used to replace all the entries but keep the attributes.

**Pull request merged**
