### PR TITLE
Dev cpp sub

### PR DESCRIPTION
**Pull request by koheiw**
Made indexing faster in C++ (#2244). Needs to test more with multi-bite UTF8 texts, but the result is promising.

```
> require(stringi)
> require(quanteda)
> type <- stri_rand_strings(1000000, 1:200)
> microbenchmark::microbenchmark(
+     quanteda3::object2fixed(data_dictionary_LSD2015[1:2], type),
+     quanteda::object2fixed(data_dictionary_LSD2015[1:2], type),
+     times = 10
+ )
Unit: seconds
                                                        expr       min        lq      mean    median
 quanteda3::object2fixed(data_dictionary_LSD2015[1:2], type) 33.959697 39.108349 46.533261 45.109721
  quanteda::object2fixed(data_dictionary_LSD2015[1:2], type)  3.826383  4.218503  5.367412  4.567814
        uq       max neval
 54.410067 63.691519    10
  6.563739  9.644364    10
```

### CODE REVIEW

**Review by kbenoit — APPROVED** [review]
Looks amazing. But would be good to try a few potentially tricky multi-byte patterns to verify under the conditions you might be uncertain about. If these tests are not added to this PR, consider adding this as an issue for adding tests later.

**Comment by koheiw** [comment]
Seems to be working 
```
> dict <- newsmap::data_dictionary_newsmap_ja
> toks <- readRDS("/twitter2/tokens.RDS") # Japanese tweets
> 
> toks2 <- tokens_select(toks, dict)
> toks3 <- quanteda3::tokens_select(toks, dict)
> identical(
+     as.list(toks2),
+     as.list(toks3)
+ )
[1] TRUE
```

**Comment by kbenoit** [comment]
Smart - you cloned the v3 branch and installed it as **quanteda3**. I should do the same.

**Comment by kbenoit** [comment]
Weird that the test-coverage CI has a test failure. It's not a coverage issue. See the Details.

**Comment by koheiw** [comment]
I don't think the error in test coverage is related to the C++ code.

**Pull request merged**
